### ISSUE TITLE
Update Chaingear UI concepts

### ISSUE THREAD

**Issue by asadovka** [cybercongress/chaingear#1008]
@asadovka commented on [Sun Jul 01 2018](https://github.com/cybercongress/cyb/issues/205)

- update ui for registry list & loading pages
- transform single page action to multipage flow with descriptions

**Comment by asadovka** [comment]
some concepts are here:

https://github.com/cybercongress/cyberdesign/blob/concept-chaingear_1008/changear/app/chaingear_design.sketch

**Comment by asadovka** [comment]
Remarks:

1. registry init
- add version description
- error message placement

2. registry view
- make another variant with action buttons placed below record

**Comment by asadovka** [comment]
Remarks:

- add beneficiaries when registry initialization
- add management block (for registry admin - claim, fund transfer etc)
- add fields : version, entry core address, registry address, link to abi
-  add beneficiaries share view
- add token ID in records
- add pause functionality
- delete registry

**Comment by xhipster** [comment]
@asadovka Please, add to design DURA template. Every layout must have clear path example

**Comment by xhipster** [comment]
I do not sure that I correctly use sketch:
<img width="1096" alt="screenshot 2018-11-15 at 20 34 30" src="https://user-images.githubusercontent.com/410789/48573779-fc395180-e915-11e8-90e9-2b6f09df6384.png">

Will need some help tomorrow

**Comment by xhipster** [comment]
<img width="1237" alt="screenshot 2018-11-15 at 20 38 05" src="https://user-images.githubusercontent.com/410789/48573905-63ef9c80-e916-11e8-8e81-6140f701d651.png">
I would love to understand how that will looks if there will no place on the screen due to a lot amount of fields?

**Comment by xhipster** [comment]
Overall: Registry page is ok, registry creation is not clear

**Comment by asadovka** [comment]
0. Common:
- add path links on screens
- name sketch artboards and pages according to paths

1. Registry creation:
- completion step - change for ready register view
- definition->compilation(with checks)-next step

2. Record creation:
- definition->compilation(with checks)-next step
- validation templates (no validation (by default)/ or unique)
- reduce amounts of active input fields to one

Registry view:
- permission control (whitelist, onlyowner,all)
- rename creator to owner (add event log in the future)
- flexible make up in the table, add horizontal scroll

**Comment by asadovka** [comment]
all new requirements will be implemented with new issues

**Comment by asadovka** [comment]
all new requirements will be implemented with new issues
