### ISSUE TITLE
Signing account do not chooses properly

### ISSUE THREAD

**Issue by xhipster** [cybercongress/chaingear#1037]
Screenshot
<img width="1173" alt="screenshot 2018-11-21 at 20 02 59" src="https://user-images.githubusercontent.com/410789/48860060-87a85c00-edc8-11e8-993b-c22d64ea5677.png">

Active account is: 0xea43e87071e7fc452bfc69948bb75ac4e02eeebd
But signing account is: 0xd09756e55a4ff30eddcfe7518d3c558d2424ba8a

Wallet screenshot:
<img width="1045" alt="screenshot 2018-11-21 at 20 04 29" src="https://user-images.githubusercontent.com/410789/48860128-b292b000-edc8-11e8-9810-c5317c9ceac3.png">

**Comment by asadovka** [comment]
@xhipster do you still have this problem?

**Comment by asadovka** [comment]
that bug doesn't appear now
