### ISSUE TITLE
Root registry structure

### ISSUE THREAD

**Issue by asadovka** [cybercongress/chaingear#1047]
1. Agree on RR structure
2. Create Chaingear registry

**Comment by asadovka** [comment]
- [programming languages](https://gist.github.com/aymen-mouelhi/82c93fbcd25f091f2c13faa5e0d61760): up to 200 names
- [common programs](https://fileinfo.com/filetypes/common): up to 100 names
- [tokens](https://coinmarketcap.com/): Up to 1k names
- [top-level domains](https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains): up to 300 names
- [top english words](https://github.com/first20hours/google-10000-english/blob/master/google-10000-english-no-swears.txt): up to 1k names
- [utf symbols](https://www.compart.com/en/unicode/category/So): up to 300 names

**Comment by asadovka** [comment]
waiting for conversation with @xhipster

**Comment by asadovka** [comment]
current implementation: only top-level domains as databases. description in DB = ipfs hash of domain main page

**Comment by xhipster** [comment]
In fact moved here https://github.com/issues/assigned
