### ISSUE TITLE
Integrate with Etherscan

### ISSUE THREAD

**Issue by abitrolly** [cybercongress/chaingear#916]
I am trying to see details on CanYa token.

![image](https://user-images.githubusercontent.com/8781107/36185622-46de7f06-114b-11e8-8f20-075572e62b04.png)

Update link forwards to page https://etherscan.io/contactus?id=4&a=0x22a7d3c296692ba0f91c631b41bdfbc702885619 which uses this form.

![image](https://user-images.githubusercontent.com/8781107/36185674-7d1423aa-114b-11e8-813e-5aa33df4a88f.png)

Full form text:
```
To update your ERC20 token information please provide us with the following information:

Firstly, check that your token contract source code has been verified.

1. Contract Address: 0x22a7d3c296692ba0f91c631b41bdfbc702885619

2. Official Site URL:

3. Link to download a 28x28png icon logo:

4. Official Contact Email Address:

5. Link to blog (optional):

6. Link to reddit (optional):

7. Link to slack (optional):

8. Link to facebook (optional):

9. Link to twitter (optional):

10. Link to bitcointalk (optional):

11. Link to github (optional):

12. Link to telegram (optional):

13. Link to whitepaper (optional):

14. CoinMarketCap Link (PriceData):
```

**Comment by litvintech** [comment]
on hold until we will make production release

**Comment by litvintech** [comment]
closed in reason of non-relevance
