### ISSUE TITLE
Migrate old chaingear to a new project

### ISSUE THREAD

**Issue by 21xhipster** [cybercongress/chaingear#927]
- pull requests closed
- issues removed
- old branches deleted

**Comment by litvintech** [comment]
- [ ] setup basic to cyber-search's repos labels
- [ ] setup advanced labels 
- [ ] migrate all chaingear-radar repos to following branches in this repo
- [ ] migrate chaingear-2 to master branch in this repo
- [ ] close non-actual pull-requests following to chaingear-radar
- [ ] close non-actual issues following to chaingear-radar
- [ ] remove non-actual branches following to chaingear-radar

**Comment by litvintech** [comment]
chaingear-2 repo -> master branch
chaingear-api repo -> chaingear-radar-browser-service
chaingear-form repo -> chaingear-radar-form
chaingear-backend repo -> chaingear-radar-backend
chaingear-golos-bot repo -> chaingear-radar-golos-bot

**Comment by litvintech** [comment]
@ninjascant @trummax please, check migrations of repos to following repos, complete migration if needed and delete repos chaingear-{form,backend,golos-bot}
