### ISSUE TITLE
Create a landing page for chaingear project

### ISSUE THREAD

**Issue by xhipster** [cybercongress/chaingear#977]
@SaveTheAles commented on [Tue May 08 2018](https://github.com/cybercongress/congress/issues/55)

---

@SaveTheAles commented on [Fri May 18 2018](https://github.com/cybercongress/congress/issues/55#issuecomment-390123309)

@xhipster @litvintech 
For now chaingear landing page available on https://chaingear.netlify.com/
Powered by netlifi, hugo and introduction theme for hugo. 
Also we waiting for landing filling with "values", "roadmap" and pictures.

**Comment by xhipster** [comment]
There is a code for netlify site?

**Comment by SaveTheAles** [comment]
Exemplary structure
![Pasted Image 1.tiff](https://shipusercontent.com/ef42062408a6fb0741e40b1d83d5a5b2/Pasted%20Image%201.tiff)

**Comment by SaveTheAles** [comment]
@xhipster @litvintech @Olga584 @asadovka @hleb-albau @Pechalka 

Chaingear landing page available https://cybercongress.github.io/chaingear/

Waiting for your review.

**Comment by arturalbov** [comment]
@SaveTheAles In my opinion pictures are too large
![screenshot from 2018-07-12 17-43-10](https://user-images.githubusercontent.com/7107023/42640515-24567554-85fb-11e8-8222-b776f48b8e74.png)

**Comment by SaveTheAles** [comment]
@cybercongress/team 
Please test this landing and report me bugs
https://cybercongress.github.io/chaingear/

**Comment by xhipster** [comment]
Please change places for ownership and economics to make the whole thing feels like `flexible ownership economics`

**Comment by xhipster** [comment]
`define that you want` => `define registry you want`

**Comment by SaveTheAles** [comment]
@xhipster done! 

Let's looking for domain for this landing

**Comment by asadovka** [comment]
https://chaingear.io
