### ISSUE TITLE
Upgrade web3 app with initial release

### ISSUE THREAD

**Issue by litvintech** [cybercongress/chaingear#978]
In this task we just fix frontend in current repository for with with new version of smart contract. 
Integration with browser will be in other task.

**Comment by asadovka** [comment]
Conversation results:

home page
- 2 lists (account registers, all registers)
- number of registers (all, account)
- edit button for account's registers
 List headers:
- name 
- symbol 
- address(admin) 
- creatin time 

  если нет то показывать сосздать как в макете


create-reaster
  name, symbol, description, tag
  status bar(states)
  подсветка кода


edit-registry
  создать страницу
  редактирование name, description
  tag 1 инпут
  редактированиеcreateion fee
  выводим name, description, sembol, address(owner) количество записей, время создание реестра


view-registry
  выводим name, description, sembol, address(owner) количество записей, время создание реестра, fee
  выводить total_fee, funded  
  данные в таблице
  add - одна кнопка создает пустую запись
  update - edit(ok, cancel)
  fund record(view all)
  view record balance ????(видят все)
  remove - видет тот кому пренадлежит, 
  clame кто запись добавил тот и owner(в текущей версии)
  добавить fund для реестра
  2 clame одна для фи другая для fund - видет тока хозяин записи
  clame видет тот кто создал реестр

**Comment by Pechalka** [comment]
in browser request v8
