### ISSUE TITLE
Deploy to mainnet

### ISSUE THREAD

**Issue by asadovka** [cybercongress/chaingear#997]
deploy chaingear's contracts
verification on etherscan

**Comment by litvintech** [comment]
- EVM's Chaingear 0.1 implementation of consensus computer driven database framework
- [Initial whitepaper](https://github.com/cybercongress/chaingear/blob/master/whitepaper.md)
- Released at [Mainnet](https://etherscan.io/address/0x02e0c94355562693B3608077732d7437bd7a78ca), [Kovan](https://kovan.etherscan.io/address/0x02e0c94355562693B3608077732d7437bd7a78ca), [Rinkeby](https://rinkeby.etherscan.io/address/0x02e0c94355562693B3608077732d7437bd7a78ca)
- Web3 application [QmQmQKkPFqLS4iNiicvAqx6aJtRpYookK8iEZjojcfEqib](https://cloudflare-ipfs.com/ipfs/QmQmQKkPFqLS4iNiicvAqx6aJtRpYookK8iEZjojcfEqib/#/)
